function createFooter(footerId) {
	var footer = $("#" + footerId);
	footer.addClass("bg-primary").addClass("footer").addClass("footer-shadow").addClass("container-fluid"); //text-light?
	footer.append($(document.createElement("div"))
		.addClass("container")
		.append($(document.createElement("div"))
			.addClass("row")
			.append($(document.createElement("div"))
				.addClass("col")
				.append($(document.createElement("a"))
					.attr("href", "index.html")
					.append($(document.createElement("p"))
						.attr("data-loc", "menuItemHomeText")))
				.append($(document.createElement("p"))
					.attr("data-loc", "menuItemGamesText"))
				.append($(document.createElement("a"))
					.attr("href", "index.html#game-squadron51")
					.append($(document.createElement("p"))
						.addClass("footer-sublink")
						.attr("data-loc", "menuItemSquadron51Text")))
				.append($(document.createElement("a"))
					.attr("href", "https://drive.google.com/drive/folders/1anMe8qc5ht1gljL7FQfc5T7QZl36vWcy?usp=sharing")
					.append($(document.createElement("p"))
						.attr("data-loc", "menuItemPressKitText"))))
			.append($(document.createElement("div"))
				.addClass("col")
				.append($(document.createElement("p"))
					.attr("data-loc", "footerEmail"))
				.append($(document.createElement("p"))
					.text("Facebook"))
				.append($(document.createElement("a"))
					.attr("href", "http://www.facebook.com/loomiarts")
					.append($(document.createElement("p"))
						.addClass("footer-sublink")
						.text("Loomiarts")))
				.append($(document.createElement("a"))
					.attr("href", "http://www.facebook.com/squadron51")
					.append($(document.createElement("p"))
						.addClass("footer-sublink")
						.attr("data-loc", "menuItemSquadron51Text"))))
			.append($(document.createElement("div"))
				.addClass("col")
				.append($(document.createElement("a"))
					.attr("href", "https://www.youtube.com/channel/UCSTsJXCSFYo009D0YAtkqSQ")
					.append($(document.createElement("p"))
						.text("Youtube")))
				.append($(document.createElement("a"))
					.attr("href", "https://twitter.com/loomiarts")
					.append($(document.createElement("p"))
						.text("Twitter"))))));
}